### ISSUE TITLE
Support for API V2

### ISSUE THREAD

**Issue by niklasravnsborg** [leonderijke/front-export#1]
Hey @leonderijke!

Awesome job with this package! Unfortunately the old Front API isn't supported anymore, so I cloned your repository and ported it to the newest Front API V2. I also added the possibility to export to `.eml` files. 😌 

https://github.com/niklasravnsborg/front-export

You can merge back to your repo if you want or do whatever! Have a nice week ☺️

**Comment by leonderijke** [comment]
Awesome work, @niklasravnsborg! API v2 support was on my to do list for a long, long time :) I'm glad you figured it out and added new features as well!

I'll just go ahead and add a note to this repository to send people to your repository.

**Comment by niklasravnsborg** [comment]
@leonderijke Nice! Thank you and thanks again for your work as well! 👍 👨‍💻

**Comment by niklasravnsborg** [comment]
@leonderijke Just an idea: Maybe you could add a link to the repo on your Gist as well: https://gist.github.com/leonderijke/525f8228fd1a1ce773e4

When I do a google search on `Front Export` I get your gist as the first result. The other results are pretty irrelevant.

<img width="860" alt="screen shot 2017-10-17 at 13 24 41" src="https://user-images.githubusercontent.com/6717303/31662427-9fff5508-b33e-11e7-8317-e265058f1a5d.png">

**Comment by leonderijke** [comment]
Done!
